### PR TITLE
Fixed Emoji Confetti Showing On Every Refresh .

### LINKED ISSUE #12: Emoji Confetti Showing On Every Refresh - Bug
right now, every refersh the emoji confettis are showing up, 
we arent looking for that. 

Ideally for now, we should _ONLY SHOW THE CONFETTIS IN THE SPLASH SCREEN_

### PR DESCRIPTION
**Pull request by anuj846k**
Fixes  #12
**Changes:**
- Added state management for confetti display
- Implemented session-based confetti control using sessionStorage
- Confetti now only triggers once per session on the initial splash screen

**Testing:**
- Verified confetti appears on the first load
- Confirmed no confetti on page refreshes or revisits
- Tested in Chrome and Firefox

This solves the issue of unnecessary confetti triggering while maintaining the initial engaging experience.

### CODE REVIEW

**Comment by piyushpatelcodes** [comment]
Hey! You did Great work. But your changes have conflicts. Please make sure to pull latest changes from this repo using command `git pull upstream main` and then merge the conflicts. After merging all the conflicts pus your code again and it will be updated in this PR. Please also add a Preview of your work in a video file.

File: src/Components/SplashScreen/index.js [hunk 1]
```diff
@@ -19,21 +19,31 @@ const container = {
 };
 
 const SplashScreen = () => {
+  const [showConfetti, setShowConfetti] = useState(false);
+
   useEffect(() => {
```
Comment (piyushpatelcodes) [inline src/Components/SplashScreen/index.js:24]: # Code Refactor Request

Hi! This is a great piece of work and a truly valuable contribution. Thank you for your efforts on this! We just have a small request for some changes in your current Pull Request.

Your code is solid, and there are no changes needed for the logic itself. We did, however, notice that you’ve used the `useEffect` hook in the `index.js` file. In our current project structure, we typically place all custom hooks (including `useEffect`) in a separate file, specifically the `useSplashScreen.js` file.

You can find this file here in the directory: [src/Components/SplashScreen](https://github.com/Dtech-Dbug/MemeTem/tree/main/src/Components/SplashScreen).

Could you kindly move all your `useEffect` hooks and any other custom hooks into the `useSplashScreen.js` file? Once done, you can simply import it into `index.js` for usage and implementation.

The reason we're suggesting this refactor is to improve code readability and make it easier for others to understand the structure. It will also help us with any future debugging or error handling, should issues arise later on.

Thanks again for your hard work! We really appreciate your contribution and look forward to your updated pull request.

**Comment by anuj846k** [comment]
> @anuj846k Hey! You did Great work. But your changes have conflicts. Please make sure to pull latest changes from this repo using command `git pull upstream main` and then merge the conflicts. After merging all the conflicts push your code again and it will be updated in this PR. Please also add a Preview of your work in a video file.


https://github.com/user-attachments/assets/9569062f-d714-4af4-897f-43c3400ca732
